"use client";

import { useEffect, useMemo, useState } from "react";
import { Bell, Building2, CalendarDays, Check, ChevronDown, ClipboardCheck, Clock3, KeyRound, LayoutDashboard, ListTodo, LogOut, Menu, Plus, Search, Settings, ShieldCheck, Users, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";

type Priority="Urgent"|"High"|"Normal"; type View="personal"|"manager";
type Task={id:number;title:string;property:string;assignee:string;due:string;time:string;priority:Priority;done:boolean;category:string};
const users=[{name:"Melissa Slabber",short:"Melissa",initials:"MS",role:"Manager",code:"2468"},{name:"Arno de Wit",short:"Arno",initials:"AD",role:"Manager",code:"1357"}];
const seedTasks:Task[]=[
 {id:1,title:"Follow up outstanding FICA",property:"14 Nantes Street, Paarl",assignee:"Arno",due:"Overdue",time:"09:00",priority:"Urgent",done:false,category:"Application"},
 {id:2,title:"Send renewal proposal to landlord",property:"8 Oak Avenue, Wellington",assignee:"Melissa",due:"Today",time:"10:30",priority:"High",done:false,category:"Renewal"},
 {id:3,title:"Complete incoming inspection report",property:"La Vie Estate · Unit 21",assignee:"Arno",due:"Today",time:"12:00",priority:"High",done:false,category:"Inspection"},
 {id:4,title:"Confirm key collection with tenant",property:"Bergendal · Unit 6",assignee:"Melissa",due:"Today",time:"14:00",priority:"Normal",done:false,category:"Tenant"},
 {id:5,title:"Upload signed lease and mandate",property:"22 Main Road, Paarl",assignee:"Arno",due:"Today",time:"15:30",priority:"Normal",done:false,category:"Admin"},
 {id:6,title:"Arrange maintenance quote",property:"Groenvlei · Unit 9",assignee:"Arno",due:"Tomorrow",time:"09:30",priority:"Normal",done:false,category:"Maintenance"},
];
const nav=[["Today",LayoutDashboard],["My tasks",ListTodo],["Calendar",CalendarDays],["Team",Users],["Properties",Building2],["Reports",ClipboardCheck]] as const;

export default function Home(){
 const[ready,setReady]=useState(false),[current,setCurrent]=useState<typeof users[number]|null>(null),[loginCode,setLoginCode]=useState(""),[loginError,setLoginError]=useState(""),[recovery,setRecovery]=useState(false),[recoverySent,setRecoverySent]=useState(false);
 const[tasks,setTasks]=useState(seedTasks),[active,setActive]=useState("Today"),[view,setView]=useState<View>("personal"),[filter,setFilter]=useState("All"),[search,setSearch]=useState(""),[mobileNav,setMobileNav]=useState(false),[dialog,setDialog]=useState(false);
 const[form,setForm]=useState({title:"",property:"",assignee:"Melissa",due:"Today",time:"09:00",priority:"Normal" as Priority});
 useEffect(()=>{const saved=localStorage.getItem("pg-user");if(saved){const found=users.find(u=>u.name===saved);if(found)setCurrent(found)}setReady(true)},[]);
 const login=()=>{const found=users.find(u=>u.code===loginCode);if(!found){setLoginError("That access code is not recognised.");return}localStorage.setItem("pg-user",found.name);setCurrent(found);setLoginError("");setView("personal")};
 const logout=()=>{localStorage.removeItem("pg-user");setCurrent(null);setMobileNav(false);setLoginCode("")};
 const visible=useMemo(()=>tasks.filter(t=>(view==="manager"||t.assignee===current?.short)&&(filter==="All"||filter==="Mine"&&t.assignee===current?.short||filter==="Urgent"&&t.priority==="Urgent"||filter==="Completed"&&t.done)&&`${t.title} ${t.property} ${t.assignee}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>Number(a.done)-Number(b.done)+({Urgent:0,High:1,Normal:2}[a.priority]-({Urgent:0,High:1,Normal:2}[b.priority]))),[tasks,filter,search,view,current]);
 const addTask=()=>{if(!form.title.trim())return;setTasks(p=>[...p,{...form,property:form.property||"General office",id:Date.now(),done:false,category:"General"}]);setForm({title:"",property:"",assignee:current?.short||"Melissa",due:"Today",time:"09:00",priority:"Normal"});setDialog(false)};
 if(!ready)return null;
 if(!current)return <main className="login-shell"><section className="login-brand"><img src="/pam-golding-gate.jpg" alt="Pam Golding Properties"/><p>PAM GOLDING</p><span>PROPERTIES</span></section><section className="login-panel">{!recovery?<div className="login-card"><span className="login-icon"><KeyRound/></span><p className="login-kicker">RENTALS ORGANISER</p><h1>Welcome back</h1><p className="login-copy">Enter the private access code provided by your manager.</p><label>Access code<input inputMode="numeric" maxLength={6} value={loginCode} onChange={e=>setLoginCode(e.target.value.replace(/\D/g,""))} onKeyDown={e=>e.key==="Enter"&&login()} placeholder="Enter your code"/></label>{loginError&&<p className="login-error">{loginError}</p>}<Button className="login-button" onClick={login}>Sign in</Button><button className="forgot" onClick={()=>setRecovery(true)}>Forgot your access code?</button><small>Demo: Melissa 2468 · Arno 1357</small></div>:<div className="login-card"><span className="login-icon"><ShieldCheck/></span><p className="login-kicker">ACCOUNT RECOVERY</p><h1>{recoverySent?"Request received":"Recover access"}</h1>{recoverySent?<><p className="login-copy">If the details match your profile, your manager will send your access code by email or WhatsApp.</p><Button className="login-button" onClick={()=>{setRecovery(false);setRecoverySent(false)}}>Back to sign in</Button></>:<><p className="login-copy">Enter the contact details registered on your staff profile.</p><label>Pam Golding email<input type="email" placeholder="name@pamgolding.co.za"/></label><label>Cellphone number<input type="tel" placeholder="e.g. 082 123 4567"/></label><Button className="login-button" onClick={()=>setRecoverySent(true)}>Send my access code</Button><button className="forgot" onClick={()=>setRecovery(false)}>Back to sign in</button></>}</div>}</section></main>;
 const isManager=view==="manager";
 return <main className="app-shell">
  <aside className={`side-panel ${mobileNav?"side-open":""}`}><div className="brand"><img className="brand-logo" src="/pam-golding-gate.jpg" alt="Pam Golding Properties"/><div><strong>Pam Golding</strong><span>PROPERTIES · RENTALS</span></div><button className="mobile-close" onClick={()=>setMobileNav(false)} aria-label="Close menu"><X/></button></div><nav>{nav.map(([label,Icon])=><button key={label} className={active===label?"active":""} onClick={()=>{setActive(label);setMobileNav(false)}}><Icon/><span>{label}</span>{label==="My tasks"&&<b>{tasks.filter(t=>!t.done&&t.assignee===current.short).length}</b>}</button>)}</nav><div className="team-card"><span className="eyebrow">MANAGEMENT TEAM</span><div className="avatar-row"><span>MS</span><span>AD</span></div><p>Paarl Rentals</p><small>2 managers · Team members to be added</small></div><div className="side-bottom"><button><Settings/>Settings</button><button className="logout-side" onClick={logout}><LogOut/>Log out</button><div className="profile"><div className="avatar">{current.initials}</div><div><strong>{current.name}</strong><span>{current.role} · Personal account</span></div><ChevronDown/></div></div></aside>{mobileNav&&<button className="scrim" onClick={()=>setMobileNav(false)} aria-label="Close menu"/>}
  <section className="workspace"><header><button className="menu-button" onClick={()=>setMobileNav(true)} aria-label="Open menu"><Menu/></button><div className="global-search"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search tasks, properties or people"/></div><div className="view-switch"><button className={!isManager?"selected":""} onClick={()=>setView("personal")}>My profile</button><button className={isManager?"selected":""} onClick={()=>setView("manager")}><ShieldCheck/>Manager</button></div><button className="icon-button" aria-label="Notifications"><Bell/><span/></button><button className="header-avatar" onClick={logout} title="Log out">{current.initials}</button></header>
   <div className="content"><div className="title-row"><div><p className="date-label">{isManager?"MANAGER OVERVIEW":"MY PERSONAL WORKSPACE"}</p><h1>{active==="Today"?`Good morning, ${current.short}`:active}</h1><p>{sectionSubtitle(active,isManager)}</p></div>{["Today","My tasks"].includes(active)&&<TaskDialog dialog={dialog} setDialog={setDialog} form={form} setForm={setForm} addTask={addTask}/>}</div>
    {active==="Today"&&<Today tasks={tasks} visible={visible} setTasks={setTasks} filter={filter} setFilter={setFilter} manager={isManager} current={current}/>} 
    {active==="My tasks"&&<TasksView visible={visible} setTasks={setTasks}/>} 
    {active==="Calendar"&&<CalendarView manager={isManager}/>} 
    {active==="Team"&&<TeamView manager={isManager} current={current}/>} 
    {active==="Properties"&&<PropertiesView/>} 
    {active==="Reports"&&<ReportsView tasks={tasks}/>} 
   </div>
  </section>
 </main>
}

function sectionSubtitle(active:string,manager:boolean){const x:Record<string,string>={Today:manager?"All team priorities and activity in one place.":"Here’s what needs your attention today.","My tasks":"Plan, prioritise and complete your rental work.",Calendar:"Meetings, inspections and deadlines from your Outlook calendar.",Team:manager?"See each person’s workload, progress and urgent items.":"Your profile, workload and daily progress.",Properties:"Tasks and activity grouped by rental property.",Reports:"A clear view of completion and overdue work."};return x[active]}
function TaskDialog({dialog,setDialog,form,setForm,addTask}:any){return <Dialog open={dialog} onOpenChange={setDialog}><DialogTrigger asChild><Button className="add-button"><Plus/>Add task</Button></DialogTrigger><DialogContent className="task-dialog"><DialogHeader><DialogTitle>Create a task</DialogTitle><DialogDescription>Assign work to yourself or a member of the rentals team.</DialogDescription></DialogHeader><div className="form-grid"><label>Task<input autoFocus value={form.title} onChange={(e:any)=>setForm({...form,title:e.target.value})} placeholder="e.g. Follow up tenant application"/></label><label>Property<input value={form.property} onChange={(e:any)=>setForm({...form,property:e.target.value})} placeholder="Address or property name"/></label><label>Assign to<select value={form.assignee} onChange={(e:any)=>setForm({...form,assignee:e.target.value})}><option value="Melissa">Melissa Slabber</option><option value="Arno">Arno de Wit</option></select></label><label>Due<select value={form.due} onChange={(e:any)=>setForm({...form,due:e.target.value})}><option>Today</option><option>Tomorrow</option><option>This week</option></select></label><label>Time<input type="time" value={form.time} onChange={(e:any)=>setForm({...form,time:e.target.value})}/></label><label>Priority<select value={form.priority} onChange={(e:any)=>setForm({...form,priority:e.target.value})}><option>Normal</option><option>High</option><option>Urgent</option></select></label></div><DialogFooter><Button variant="outline" onClick={()=>setDialog(false)}>Cancel</Button><Button className="add-button" onClick={addTask}>Create task</Button></DialogFooter></DialogContent></Dialog>}
function TaskRows({items,setTasks}:{items:Task[],setTasks:any}){return <div className="task-list">{items.length?items.map(task=><article key={task.id} className={`${task.done?"done":""} ${task.priority.toLowerCase()}`}><Checkbox checked={task.done} onCheckedChange={()=>setTasks((ts:Task[])=>ts.map(t=>t.id===task.id?{...t,done:!t.done}:t))}/><div className="task-copy"><div className="task-top"><h3>{task.title}</h3>{task.priority!=="Normal"&&<span className={`priority ${task.priority.toLowerCase()}`}>{task.priority}</span>}</div><p><Building2/>{task.property}</p><div className="task-meta"><span className="person-pill">{task.assignee.slice(0,1)} · {task.assignee}</span><span className={task.due==="Overdue"?"overdue":""}><CalendarDays/>{task.due}</span><span><Clock3/>{task.time}</span></div></div><button className="more">•••</button></article>):<div className="empty-state"><Check/><h3>Nothing here</h3><p>No tasks match this view.</p></div>}</div>}
function Today({tasks,visible,setTasks,filter,setFilter,manager,current}:any){const scope=manager?tasks:tasks.filter((t:Task)=>t.assignee===current.short);return <><div className="summary-grid"><article><span className="summary-icon red"><Clock3/></span><div><small>NEEDS ATTENTION</small><strong>{scope.filter((t:Task)=>!t.done&&t.priority==="Urgent").length}</strong><p>Urgent or overdue</p></div></article><article><span className="summary-icon gold"><ListTodo/></span><div><small>DUE TODAY</small><strong>{scope.filter((t:Task)=>!t.done&&t.due==="Today").length}</strong><p>{manager?"Across the team":"Assigned to me"}</p></div></article><article><span className="summary-icon green"><Check/></span><div><small>COMPLETED</small><strong>{scope.filter((t:Task)=>t.done).length}</strong><p>Today</p></div></article></div><div className="main-grid"><section className="task-panel"><div className="panel-heading"><div><h2>Today’s priorities</h2><p>Automatically ordered by urgency and due time</p></div></div><div className="filters">{["All","Mine","Urgent","Completed"].map(x=><button key={x} className={filter===x?"selected":""} onClick={()=>setFilter(x)}>{x}</button>)}</div><TaskRows items={visible} setTasks={setTasks}/></section><aside className="right-column"><CalendarCard/><TeamProgress manager={manager}/></aside></div></>}
function TasksView({visible,setTasks}:any){return <section className="task-panel standalone"><div className="panel-heading"><div><h2>Task list</h2><p>All work in your selected profile view</p></div><span className="count-pill">{visible.length} tasks</span></div><TaskRows items={visible} setTasks={setTasks}/></section>}
function CalendarCard(){return <section className="calendar-card"><div className="panel-heading"><div><h2>Today’s calendar</h2><p>Outlook calendar</p></div></div><Meeting time="09:30" title="Rental pipeline meeting" place="Paarl office · Boardroom"/><Meeting time="13:00" title="Landlord meeting" place="La Vie Estate · Unit 21"/><Button variant="outline" className="outlook"><CalendarDays/>Connect my Outlook calendar</Button></section>}
function Meeting({time,title,place}:any){return <div className="meeting"><time>{time}</time><div className="meeting-line greenline"/><div><strong>{title}</strong><span>{place}</span><small>60 minutes</small></div></div>}
function CalendarView({manager}:any){return <div className="calendar-layout"><section className="week-card"><div className="week-head"><button>←</button><h2>8–14 September 2026</h2><button>→</button></div>{["Tue 8","Wed 9","Thu 10","Fri 11"].map((d,i)=><div className="day-row" key={d}><strong>{d}</strong><div>{i===0?<><Meeting time="09:30" title="Rental pipeline meeting" place="Paarl office"/><Meeting time="13:00" title="Landlord meeting" place="La Vie Estate"/></>:i===1?<Meeting time="10:00" title="Incoming inspection" place="Groenvlei"/>:<p className="no-events">No meetings scheduled</p>}</div></div>)}</section><aside><CalendarCard/><p className="info-note">{manager?"Manager view can display the team’s availability once each person connects Outlook.":"Only your own calendar is displayed in My Profile view."}</p></aside></div>}
function TeamProgress({manager}:any){return <section className="team-progress"><div className="panel-heading"><div><h2>{manager?"Management progress":"My progress"}</h2><p>Individual work today</p></div></div>{(manager?[["Melissa Slabber","MS",3,5],["Arno de Wit","AD",2,4]]:[["Melissa Slabber","MS",3,5]]).map(([n,i,d,t])=><div className="member" key={String(n)}><span className="member-avatar">{i}</span><div><strong>{n}</strong><div className="progress"><i style={{width:`${Number(d)/Number(t)*100}%`}}/></div></div><small>{d}/{t}</small></div>)}</section>}
function TeamView({manager,current}:any){if(!manager)return <section className="profile-page"><div className="large-avatar">{current.initials}</div><h2>{current.name}</h2><p>Manager · Paarl Rentals</p><div className="profile-stats"><article><strong>2</strong><span>Open tasks</span></article><article><strong>0</strong><span>Overdue</span></article><article><strong>60%</strong><span>Completed</span></article></div></section>;return <div className="people-grid">{users.map((u,i)=><article key={u.name}><div className="person-top"><span className="large-avatar">{u.initials}</span><span className={i?"status busy":"status"}>{i?"1 urgent":"On track"}</span></div><h2>{u.name}</h2><p>Manager · Paarl Rentals</p><div className="person-numbers"><span><strong>{i?4:5}</strong> tasks</span><span><strong>{i?2:3}</strong> done</span></div><Button variant="outline">View profile</Button></article>)}</div>}
function PropertiesView(){return <div className="property-grid">{[["14 Nantes Street","Paarl","FICA overdue",2],["La Vie Estate · Unit 21","Paarl","Inspection today",3],["8 Oak Avenue","Wellington","Renewal in progress",1],["Bergendal · Unit 6","Paarl","Key collection",1]].map(([n,a,s,c])=><article key={String(n)}><span className="property-icon"><Building2/></span><div><h2>{n}</h2><p>{a}</p><small>{s}</small></div><b>{c} tasks</b></article>)}</div>}
function ReportsView({tasks}:any){const done=tasks.filter((t:Task)=>t.done).length;return <div className="report-grid"><article><p>Task completion</p><strong>{Math.round(done/tasks.length*100)}%</strong><div className="report-bar"><i style={{width:`${Math.round(done/tasks.length*100)}%`}}/></div><small>{done} of {tasks.length} completed</small></article><article><p>Current workload</p><strong>{tasks.filter((t:Task)=>!t.done).length}</strong><small>Open tasks across the team</small></article><article><p>Overdue</p><strong className="red-number">{tasks.filter((t:Task)=>t.due==="Overdue"&&!t.done).length}</strong><small>Needs manager attention</small></article></div>}
