"use client";

import { useMemo, useState } from "react";
import { Bell, Building2, CalendarDays, Check, ChevronDown, ClipboardCheck, Clock3, LayoutDashboard, ListTodo, Menu, Plus, Search, Settings, Users, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";

type Priority = "Urgent" | "High" | "Normal";
type Task = { id:number; title:string; property:string; assignee:string; due:string; time:string; priority:Priority; done:boolean; category:string };
const seedTasks:Task[]=[
 {id:1,title:"Follow up outstanding FICA",property:"14 Nantes Street, Paarl",assignee:"Arno",due:"Overdue",time:"09:00",priority:"Urgent",done:false,category:"Application"},
 {id:2,title:"Send renewal proposal to landlord",property:"8 Oak Avenue, Wellington",assignee:"Melissa",due:"Today",time:"10:30",priority:"High",done:false,category:"Renewal"},
 {id:3,title:"Complete incoming inspection report",property:"La Vie Estate · Unit 21",assignee:"Arno",due:"Today",time:"12:00",priority:"High",done:false,category:"Inspection"},
 {id:4,title:"Confirm key collection with tenant",property:"Bergendal · Unit 6",assignee:"Melissa",due:"Today",time:"14:00",priority:"Normal",done:false,category:"Tenant"},
 {id:5,title:"Upload signed lease and mandate",property:"22 Main Road, Paarl",assignee:"Arno",due:"Today",time:"15:30",priority:"Normal",done:false,category:"Admin"},
 {id:6,title:"Arrange maintenance quote",property:"Groenvlei · Unit 9",assignee:"Arno",due:"Tomorrow",time:"09:30",priority:"Normal",done:false,category:"Maintenance"},
];
const nav=[["Today",LayoutDashboard],["My tasks",ListTodo],["Calendar",CalendarDays],["Team",Users],["Properties",Building2],["Reports",ClipboardCheck]] as const;

export default function Home(){
 const[tasks,setTasks]=useState(seedTasks); const[active,setActive]=useState("Today"); const[filter,setFilter]=useState("All"); const[search,setSearch]=useState(""); const[mobileNav,setMobileNav]=useState(false); const[dialog,setDialog]=useState(false);
 const[form,setForm]=useState({title:"",property:"",assignee:"Melissa",due:"Today",time:"09:00",priority:"Normal" as Priority});
 const visible=useMemo(()=>tasks.filter(t=>(filter==="All"||filter==="Mine"&&t.assignee==="Melissa"||filter==="Urgent"&&t.priority==="Urgent"||filter==="Completed"&&t.done)&&`${t.title} ${t.property} ${t.assignee}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>Number(a.done)-Number(b.done)+({Urgent:0,High:1,Normal:2}[a.priority]-({Urgent:0,High:1,Normal:2}[b.priority]))),[tasks,filter,search]);
 const addTask=()=>{if(!form.title.trim())return;setTasks(p=>[...p,{...form,property:form.property||"General office",id:Date.now(),done:false,category:"General"}]);setForm({title:"",property:"",assignee:"Melissa",due:"Today",time:"09:00",priority:"Normal"});setDialog(false)};
 return <main className="app-shell">
  <aside className={`side-panel ${mobileNav?"side-open":""}`}><div className="brand"><div className="brand-mark">PG</div><div><strong>Pam Golding</strong><span>Rentals organiser</span></div><button className="mobile-close" onClick={()=>setMobileNav(false)} aria-label="Close menu"><X/></button></div><nav>{nav.map(([label,Icon])=><button key={label} className={active===label?"active":""} onClick={()=>{setActive(label);setMobileNav(false)}}><Icon/><span>{label}</span>{label==="My tasks"&&<b>2</b>}</button>)}</nav><div className="team-card"><span className="eyebrow">MANAGEMENT TEAM</span><div className="avatar-row"><span>MS</span><span>AD</span></div><p>Paarl Rentals</p><small>2 managers · Team members to be added</small></div><div className="side-bottom"><button><Settings/>Settings</button><div className="profile"><div className="avatar">MS</div><div><strong>Melissa Slabber</strong><span>Manager · Personal account</span></div><ChevronDown/></div></div></aside>
  {mobileNav&&<button className="scrim" onClick={()=>setMobileNav(false)} aria-label="Close menu"/>}
  <section className="workspace"><header><button className="menu-button" onClick={()=>setMobileNav(true)} aria-label="Open menu"><Menu/></button><div className="global-search"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search tasks, properties or people"/></div><button className="icon-button" aria-label="Notifications"><Bell/><span/></button><div className="header-avatar">MO</div></header>
   <div className="content"><div className="title-row"><div><p className="date-label">TUESDAY, 8 SEPTEMBER</p><h1>{active==="Today"?"Good morning, Melissa":active}</h1><p>{active==="Today"?"Here’s what needs your attention today.":"Your rental team workspace."}</p></div>
    <Dialog open={dialog} onOpenChange={setDialog}><DialogTrigger asChild><Button className="add-button"><Plus/>Add task</Button></DialogTrigger><DialogContent className="task-dialog"><DialogHeader><DialogTitle>Create a task</DialogTitle><DialogDescription>Assign work to yourself or a member of the rentals team.</DialogDescription></DialogHeader><div className="form-grid"><label>Task<input autoFocus value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="e.g. Follow up tenant application"/></label><label>Property<input value={form.property} onChange={e=>setForm({...form,property:e.target.value})} placeholder="Address or property name"/></label><label>Assign to<select value={form.assignee} onChange={e=>setForm({...form,assignee:e.target.value})}><option value="Melissa">Melissa Slabber</option><option value="Arno">Arno de Wit</option></select></label><label>Due<select value={form.due} onChange={e=>setForm({...form,due:e.target.value})}><option>Today</option><option>Tomorrow</option><option>This week</option></select></label><label>Time<input type="time" value={form.time} onChange={e=>setForm({...form,time:e.target.value})}/></label><label>Priority<select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value as Priority})}><option>Normal</option><option>High</option><option>Urgent</option></select></label></div><DialogFooter><Button variant="outline" onClick={()=>setDialog(false)}>Cancel</Button><Button className="add-button" onClick={addTask}>Create task</Button></DialogFooter></DialogContent></Dialog>
   </div>
   <div className="summary-grid"><article><span className="summary-icon red"><Clock3/></span><div><small>NEEDS ATTENTION</small><strong>{tasks.filter(t=>!t.done&&t.priority==="Urgent").length}</strong><p>1 task is overdue</p></div></article><article><span className="summary-icon gold"><ListTodo/></span><div><small>DUE TODAY</small><strong>{tasks.filter(t=>!t.done&&t.due==="Today").length}</strong><p>Across your team</p></div></article><article><span className="summary-icon green"><Check/></span><div><small>COMPLETED</small><strong>{tasks.filter(t=>t.done).length}</strong><p>Today</p></div></article></div>
   <div className="main-grid"><section className="task-panel"><div className="panel-heading"><div><h2>Today’s priorities</h2><p>Automatically ordered by urgency and due time</p></div><button>View all <span>→</span></button></div><div className="filters">{["All","Mine","Urgent","Completed"].map(x=><button key={x} className={filter===x?"selected":""} onClick={()=>setFilter(x)}>{x}{x==="All"&&<span>{tasks.filter(t=>!t.done).length}</span>}</button>)}</div><div className="task-list">{visible.length?visible.map(task=><article key={task.id} className={`${task.done?"done":""} ${task.priority.toLowerCase()}`}><Checkbox checked={task.done} onCheckedChange={()=>setTasks(ts=>ts.map(t=>t.id===task.id?{...t,done:!t.done}:t))} aria-label={`Mark ${task.title} complete`}/><div className="task-copy"><div className="task-top"><h3>{task.title}</h3>{task.priority!=="Normal"&&<span className={`priority ${task.priority.toLowerCase()}`}>{task.priority}</span>}</div><p><Building2/>{task.property}</p><div className="task-meta"><span className="person-pill">{task.assignee.slice(0,1)} · {task.assignee}</span><span className={task.due==="Overdue"?"overdue":""}><CalendarDays/>{task.due}</span><span><Clock3/>{task.time}</span></div></div><button className="more">•••</button></article>):<div className="empty-state"><Check/><h3>Nothing here</h3><p>Try another filter or add a task.</p></div>}</div></section>
    <aside className="right-column"><section className="calendar-card"><div className="panel-heading"><div><h2>Today’s calendar</h2><p>Melissa’s Outlook calendar</p></div><button className="calendar-link">Open</button></div><div className="meeting"><time>09:30</time><div className="meeting-line redline"/><div><strong>Rental pipeline meeting</strong><span>Paarl office · Boardroom</span><small>45 min · 5 attendees</small></div></div><div className="meeting"><time>13:00</time><div className="meeting-line goldline"/><div><strong>Landlord meeting</strong><span>La Vie Estate · Unit 21</span><small>60 min · With Pieter Nel</small></div></div><Button variant="outline" className="outlook"><CalendarDays/>Connect my Outlook calendar</Button></section><section className="team-progress"><div className="panel-heading"><div><h2>Management progress</h2><p>Individual work today</p></div></div>{[["Melissa Slabber","MS",3,5],["Arno de Wit","AD",2,4]].map(([name,initials,done,total])=><div className="member" key={String(name)}><span className="member-avatar">{initials}</span><div><strong>{name}</strong><div className="progress"><i style={{width:`${Number(done)/Number(total)*100}%`}}/></div></div><small>{done}/{total}</small></div>)}</section></aside>
   </div></div>
  </section>
 </main>
}
